using System;
using System.Runtime.InteropServices;

namespace DataModel
{
    /**
     * Author : ICSC 余士鵬
     * Desc : MMS Snd Msg Model
     * **/
    public class MMSToL2Msg
    {
        [Serializable]
        [StructLayout(LayoutKind.Sequential, Pack = 1)]
        public class PDI
        {
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Length = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)]
            public char[] Code = new char[6];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
            public char[] Date = new char[8];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)]
            public char[] Time = new char[6];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] SendWho = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] RcvWho = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] FuncCode = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
            public char[] Plan_No = new char[10];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] Mat_Seq_No = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] Plan_Sort = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
            public char[] Entry_Coil_No = new char[20];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Entry_Coil_Thick = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Entry_Coil_Width = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Entry_Coil_Weight = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Entry_Coil_Length = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Entry_Coil_Inner = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Entry_Coil_Dcos = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Sleeve_Type_Code = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Sleeve_diamter = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] Paper_Req_Code = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] Paper_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Head_Paper_Length = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Head_Paper_Width = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Tail_Paper_Length = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Tail_Paper_Width = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Ts_Stand_Max = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Ts_Stand_Min = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
            public char[] St_No = new char[8];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Density = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] REPAIR_TYPE = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] Surface_Finishing_Code = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] Surface_Accuracy = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] Base_Surface = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] Uncoiler_Direction = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
            public char[] Out_Mat_No = new char[20];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] Out_Paper_Req_Code = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] Out_Paper_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Out_Sleeve_Diamter = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Out_Sleeve_Type_Code = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Out_Strap_Num = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] Leader_Flag = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] Samp_Flag = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] Sample_Frqn_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
            public char[] Sample_Lot_No = new char[20];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] Coil_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] Wholebacklog_Code = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] Next_Wholebacklog_Code = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] Trim_Flag = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Out_Mat_Width = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Out_Mat_Width_Max = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Out_Mat_Width_Min = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Out_Mat_Thickness = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Out_Coil_Inner = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
            public char[] Order_No = new char[10];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Order_Wt_Max = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Order_Wt_Min = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Order_Wt = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] Dividing_Flag = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] Dividing_Num = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Orderwt_1 = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Orderwt_2 = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Orderwt_3 = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Orderwt_4 = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Orderwt_5 = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Orderwt_6 = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
            public char[] Order_No_1 = new char[10];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
            public char[] Order_No_2 = new char[10];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
            public char[] Order_No_3 = new char[10];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
            public char[] Order_No_4 = new char[10];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
            public char[] Order_No_5 = new char[10];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
            public char[] Order_No_6 = new char[10];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D01_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D01_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D01_Sid = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D01_Pos_W = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D01_Pos_L_Start = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D01_Pos_L_End = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D01_Level = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D01_Percent = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D01_QGRADE = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D02_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D02_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D02_Sid = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D02_Pos_W = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D02_Pos_L_Start = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D02_Pos_L_End = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D02_Level = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D02_Percent = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D02_QGRADE = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D03_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D03_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D03_Sid = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D03_Pos_W = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D03_Pos_L_Start = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D03_Pos_L_End = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D03_Level = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D03_Percent = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D03_QGRADE = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D04_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D04_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D04_Sid = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D04_Pos_W = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D04_Pos_L_Start = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D04_Pos_L_End = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D04_Level = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D04_Percent = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D04_QGRADE = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D05_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D05_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D05_Sid = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D05_Pos_W = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D05_Pos_L_Start = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D05_Pos_L_End = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D05_Level = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D05_Percent = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D05_QGRADE = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D06_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D06_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D06_Sid = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D06_Pos_W = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D06_Pos_L_Start = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D06_Pos_L_End = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D06_Level = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D06_Percent = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D06_QGRADE = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D07_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D07_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D07_Sid = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D07_Pos_W = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D07_Pos_L_Start = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D07_Pos_L_End = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D07_Level = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D07_Percent = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D07_QGRADE = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D08_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D08_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D08_Sid = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D08_Pos_W = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D08_Pos_L_Start = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D08_Pos_L_End = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D08_Level = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D08_Percent = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D08_QGRADE = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D09_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D09_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D09_Sid = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D09_Pos_W = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D09_Pos_L_Start = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D09_Pos_L_End = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D09_Level = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D09_Percent = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D09_QGRADE = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D10_Code = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D10_Origin = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D10_Sid = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D10_Pos_W = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D10_Pos_L_Start = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] D10_Pos_L_End = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D10_Level = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] D10_Percent = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] D10_QGRADE = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 50)]
            public char[] Test_Plan_No = new char[50];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 500)]
            public char[] Qc_Remark = new char[500];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Head_Off_Gauge = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)]
            public char[] Tail_Off_Gauge = new char[5];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] Surface_Accu_Code_In = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] Surface_Accu_Code_Out = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 50)]
            public char[] Sg_Sign = new char[50];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)]
            public char[] Process_Code = new char[6];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 200)]
            public char[] Customer_Name_E = new char[200];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 200)]
            public char[] Customer_Name_C = new char[200];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
            public char[] Customer_No = new char[20];

        }

        [Serializable]
        [StructLayout(LayoutKind.Sequential, Pack = 1)]
        public class CoilSchedule
        {
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public char[] Length = new char[4];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)]
            public char[] Code = new char[6];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
            public char[] Date = new char[8];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)]
            public char[] Time = new char[6];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] SendWho = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public char[] RcvWho = new char[2];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)]
            public char[] FuncCode = new char[1];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
            public char[] CoilNo = new char[20];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public char[] NumberOfCoils = new char[3];
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6000)]
            public char[] EntryCoilNo = new char[6000];

        }
    }
}
